### ISSUE TITLE
Tweet actu

### ISSUE THREAD

**Issue by 2016floreza** [oser-cs/oser-frontend#7]
Sur page actu, il n'affiche les tweets qu'une fois qu'on a appuyé dessus et qu'on revient sur la page

**Comment by florimondmanca** [comment]
Oui, j'avais déjà remarqué ce problème…

## Reproduction du bug

- Je démarre le serveur Angular
- Je vais à l'adresse `/showcase` et j'arrive sur le site vitrine
- Je clique sur "Actualités", et le tweet feed n'apparaît pas et est remplacé par "Tweets de @OSER_CS"

![img1](https://user-images.githubusercontent.com/15911462/36340208-725dfd8e-13d8-11e8-9c0b-c155e94db783.png)

- Je rafraichis la page et là le tweet feed apparaît après qq secondes !

![img2](https://user-images.githubusercontent.com/15911462/36340210-7979e95c-13d8-11e8-96d6-cc20210486c3.png)

C'est bien ça que vous avez ?

## Explications

J'ai intégré le feed Twitter avec [Twitter Publish](https://publish.twitter.com/). Ça génère un snippet à mettre directement dans le HTML, avec une balise `<a>` et une balise `<script>`.

```html
<a class="twitter-timeline" href="https://twitter.com/OSER_CS?ref_src=twsrc%5Etfw">Tweets by OSER_CS</a>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
```

Du coup logiquement au début je l'avais mis dans le `news-page.component.html`. Sauf que : Angular "retire" automatiquement les balises `<script>` dans les templates, apparemment c'est [une mesure contre le XSS](https://angular.io/guide/security#xss) (injection de JS malveillant).

Du coup la solution que j'ai trouvé c'est garder le `<a>` dans le template et de mettre le `<script>` dans le `index.html` (seul endroit où Angular autorise les `<script>`), et ça fonctionne mais ce bug persiste.

## Origine possible

J'imagine que le bug provient d'interférences entre le routeur et le chargement des scripts depuis le `index.html`. Peut-être que le JS de Twitter ne reconnaît pas les changements de "page" provoqués par le routeur et ne fonctionne que pour une page donnée (il s'injecte p-e dans du HTML fixe et ne fonctionne plus si celui-ci change…), ce qui expliquerait qu'il faille recharger la page...

À mon avis il doit y avoir moyen de faire autrement. Je vais voir si des packages existants permettent de faire ça + proprement !

**Comment by florimondmanca** [comment]
J'ai trouvé une solution, voir #11 :wink:
