### ISSUE TITLE
Article Actu

### ISSUE THREAD

**Issue by 2016floreza** [oser-cs/oser-frontend#8]
Sur la page actu, aucun article ne s'affiche et cela malgré le browser

**Comment by florimondmanca** [comment]
Ça affiche quand même "Pas d'articles pour le moment ?"

Les articles sont fournis par le back maintenant. Il faut que le serveur Django tourne. Checkez [la doc](http://oser-website.readthedocs.io/fr/latest/installation.html) mais je crois que @2016floreza avait réussi à l'installer déjà. 👍 

Vérifiez que le serveur tourne en allant à [](localhost:8000/api/articles), le front récupère les articles à cette URL.

**Comment by florimondmanca** [comment]
Pour info, lorsque vous installez le back la DB est vide. La doc décrit l'étape pour [configurer et peupler la DB](http://oser-website.readthedocs.io/fr/latest/installation.html#configuration-de-la-base-de-donnees). Il faut faire l'étape population car sinon il n'y aura pas d'articles dans la DB… :wink:

**Comment by florimondmanca** [comment]
@AurianeStrasser2 Tu me diras si avec le backend hébergé ça fonctionne. :) Comme ça on pourra clore !
