### ISSUE TITLE
Slides Nos Actions

### ISSUE THREAD

**Issue by 2016floreza** [oser-cs/oser-frontend#9]
Sur la page nos actions, il ne reconnait les slides que sur firefox. 
Sur edge, il manque les slides 2 et 3. 
Sur chrome les flèches sont absentes

**Comment by florimondmanca** [comment]
Sous Chrome, les flèches sont bien là chez moi. Vous êtes sûrs de l'installation ? La console de Chrome n'affiche pas d'erreur ?

![chrome](https://user-images.githubusercontent.com/15911462/36340525-1c1aefc0-13df-11e8-8e82-1df22bb27d05.png)

**Comment by florimondmanca** [comment]
@2016floreza Pour Edge, tu veux dire que quand vous cliquez sur les flèches ça ne défile pas ?

**Comment by florimondmanca** [comment]
Up 😛

**Comment by florimondmanca** [comment]
Vu que ça a l'air résolu, je ferme l'issue :)
